### ISSUE TITLE
Is `~/.npm-rfc/` a better temp folder than `/tmp/ietf-rfc`?

### ISSUE THREAD

**Issue by leesei** [jwerle/rfc#4]
I'm also thinking of allowing the user to export and bookmark rfcs, it would be better if there is a user's folder for this app.

**Comment by jwerle** [comment]
or `~/.rfc`? I like the idea of moving away from using `$TMPDIR`

**Comment by leesei** [comment]
I'm afraid the `~/.rfc` namespace is too generic and might cause a conflict.
Also, some programs use `.d` suffix to denote a directory, I also recommend that.

Here are my updated suggestions:
```
~/.npm-rfc.d/
~/.node-rfc.d/
~/.rfc.d/
```

**Comment by jwerle** [comment]
I think leaving `npm` and `node` out of the name is a good idea. These aren't RFCs for node or npm... `~/.rfc.d` could work

**Comment by leesei** [comment]
K, are you free to implement this?
I can help within week's time.

**Comment by jwerle** [comment]
I'm very busy for the next week. I will happily accept a PR!

**Comment by jwerle** [comment]
No problem !

**Comment by leesei** [comment]
Merged #6.
