### ISSUE TITLE
Error accessing `/usr/local/share/man/man1` during install

### ISSUE THREAD

**Issue by leesei** [jwerle/rfc#5]
I'm encounter this on Mint 15 and LDME.

```sh
$ npm install -g rfc
/home/leesei/.nvm/versions/node/v0.12.1/bin/rfc -> /home/leesei/.nvm/versions/node/v0.12.1/lib/node_modules/rfc/bin/rfc

> rfc@0.0.8 install /home/leesei/.nvm/versions/node/v0.12.1/lib/node_modules/rfc
> make man

install rfc.1 /usr/local/share/man/man1
install: cannot create regular file ‘/usr/local/share/man/man1’: Permission denied
```

A workaround is `sudo chmod 777 /usr/local/share/man/`.

**Comment by jwerle** [comment]
Yeah you should have rights to that directory or use `sudo`

**Comment by leesei** [comment]
I think I encountered this issue 'cause I use `nvm` to avoid `sudo`-ing for
global packages.
How about adding `sudo` for the `make` target?
But that would break unattended installs and I doubt if it is a good
practice.

I'll try to look for any way to install manpage without sudo.

**Comment by leesei** [comment]
Update: I'm using [nvm](https://github.com/creationix/nvm) and found that the man page actually symlinked to `~/.nvm/versions/node/v0.12.3/share/man/man1`, which is in my `$MANPATH`.

I'm not sure how this works, just to share this finding for further investigation.
